spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/traassist
    username: trauser
    password: trapass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

ollama:
  base-url: http://localhost:11434
  embedding-model: nomic-embed-text
  chat-model: mistral

telegram:
  bot-token:
  bot-username: